[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Essential runtime for Next.js on Netlify
[build.processing]
  skip_processing = false

# Redirect all server-side routes to Next.js
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
