// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://mbmbauqjdgbisaxkfpbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ibWJhdXFqZGdiaXNheGtmcGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODMxMDYsImV4cCI6MjA1Nzg1OTEwNn0.VYhZeZ1ez9QEnJKBRD0tyenuLC8YChSzem8CoUQ6_QI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
